language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t larrymenta/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true larrymenta/docker-react npm run test